---
# The following tasks are only needed in the Docker environment, for testing.
- name: Ensure SSH is installed.
  package:
    name: openssh-server
    state: present

- name: Set variables for Docker-based cluster testing.
  set_fact:
    kubernetes_kubelet_extra_args: '--node-ip={{ ansible_host }} --fail-swap-on=false'
    kubernetes_join_command_extra_opts: '--ignore-preflight-errors=Swap,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables'
    docker_users: []
