version: '3'

services:
  controller:
    container_name: controller
    privileged: true
    image: geerlingguy/docker-debian10-ansible
    networks:
      kube_net:
        ipv4_address: 192.168.7.9
    volumes:
      - ./:/opt/ansible/:rw,delegated
      - /var/run/docker.sock:/var/run/docker.sock

  kube1:
    container_name: kube1
    image: geerlingguy/docker-debian10-ansible
    networks:
      kube_net:
        ipv4_address: 192.168.7.2

  kube2:
    container_name: kube2
    image: geerlingguy/docker-debian10-ansible
    networks:
      kube_net:
        ipv4_address: 192.168.7.3

  kube3:
    container_name: kube3
    image: geerlingguy/docker-debian10-ansible
    networks:
      kube_net:
        ipv4_address: 192.168.7.4

networks:
  kube_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.7.0/24
