version: '3.7'

services:
  kube1:
    container_name: kube1
    privileged: true
    image: geerlingguy/docker-debian10-ansible
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/docker/daemon.json:/etc/docker/daemon.json:ro
      - /tmp/docker/resolv.conf:/etc/resolv.conf:ro
      - type: bind
        source: /tmp/docker/kube1
        target: /var/lib/docker
    networks:
      kube_net:
        ipv4_address: 192.168.7.2

  kube2:
    container_name: kube2
    privileged: true
    image: geerlingguy/docker-debian10-ansible
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/docker/daemon.json:/etc/docker/daemon.json:ro
      - /tmp/docker/resolv.conf:/etc/resolv.conf:ro
      - type: bind
        source: /tmp/docker/kube2
        target: /var/lib/docker
    networks:
      kube_net:
        ipv4_address: 192.168.7.3

  kube3:
    container_name: kube3
    privileged: true
    image: geerlingguy/docker-debian10-ansible
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/docker/daemon.json:/etc/docker/daemon.json:ro
      - /tmp/docker/resolv.conf:/etc/resolv.conf:ro
      - type: bind
        source: /tmp/docker/kube3
        target: /var/lib/docker
    networks:
      kube_net:
        ipv4_address: 192.168.7.4

networks:
  kube_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.7.0/24
