---
- hosts: kube
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include_tasks: tasks/setup.yml

  roles:
    - role: geerlingguy.security
      tags: ['security']
      when: ansible_connection != 'docker'

    - role: geerlingguy.swap
      tags: ['swap']
      when: ansible_connection != 'docker'

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']

    # - role: geerlingguy.docker
    #   tags: ['docker']

    # - role: geerlingguy.kubernetes
    #   tags: ['kubernetes']
