---
- hosts: kube
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.security
      tags: ['security']

    - role: geerlingguy.swap
      tags: ['swap']
      when: ansible_connection != 'docker'

    - role: geerlingguy.docker
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']
